BI-7487 Add insolvency company number comparator
companieshouse/data-reconciliation pull request #43
Opened 2021-06-18 16:31 UTC by dlgroves-ch

* Compare company numbers with insolvency cases on Oracle and MongoDB.
* Aggregate insolvency case comparison results into a new comparison
group named Company insolvency.
* Generalise MongoDB distinct service wrapper route.

2021-06-23 08:55 UTC, kinpang-CH approved these changes

2021-06-24 07:58 UTC, phudson-ch approved these changes

2021-06-24 09:17 UTC, cgregoryCH approved these changes

2021-06-25 14:11 UTC, phudson-ch requested changes
Period separator has been used instead of underscore.

2021-06-25 14:11 UTC, phudson-ch commented on src/main/java/uk/gov/companieshouse/reconciliation/insolvency/InsolvencyCompanyNumberCompareMongoDBOracle.java
> +        from("{{endpoint.insolvency.company_number.mongo_oracle.timer}}")
Incorrect period separator: `company_number.mongo_oracle` should read `company_number_mongo_oracle`

2021-06-25 14:11 UTC, phudson-ch commented on src/main/resources/application.properties
> +endpoint.insolvency.company_number.mongo_oracle.timer=timer:insolvency_company_number?repeatCount=1&delay=${INSOLVENCY_COMPANY_NUMBER_MONGO_ORACLE_DELAY}
Incorrect period separator: company_number.mongo_oracle should read company_number_mongo_oracle

2021-06-25 14:11 UTC, phudson-ch commented on src/test/resources/application-stubbed.properties
> +endpoint.insolvency.company_number.mongo_oracle.timer=direct:insolvency_company_number_mongo_oracle_trigger
Incorrect period separator: company_number.mongo_oracle should read company_number_mongo_oracle

2021-06-28 08:27 UTC, phudson-ch approved these changes

2021-06-28 08:30 UTC, merged